# Maximum number of vehicles
VehNum: 5

# max speed
maxSpeed: 0.5

# use robust formation management
useRobustForm: True
#useRobustForm: False

# use external DP controller
useExtCon: False
kdp: 0.25

useRepel: True
# Force repeling controller gain
kf: 3.5
# Force correction factor
kd: 0.0
# Force vector corr factor
ni: 0.5
# repel radius
rf: 2.0

# Direct graph matrix for 
#DGMat: [0, 1, 1, 0, 0,
#        1, 0, 1, 0, 0,
#        1, 1, 0, 0, 0,
#        0, 0, 0, 0, 0,
#        0, 0, 0, 0, 0]
DGMat: [0, 1, 1, 1, 1,
        1, 0, 1, 1, 1,
        1, 1, 0, 1, 1,
        1, 1, 1, 0, 1,
        1, 1, 1, 1, 0]

# Gain matrix
GMat: [   0, 0.08, 0.08, 0.08, 0.08,
       0.08,    0, 0.08, 0.08, 0.08,
       0.08, 0.08,    0, 0.08, 0.08,
       0.08, 0.08, 0.08,    0, 0.08,
       0.08, 0.08, 0.08, 0.08,    0]

# Formation distances matrix
formX: [    0,   3,  1.5, 0, 0,
           -3,   0, -1.5, 0, 0,
         -1.5, 1.5,    0, 0, 0,
            0,   0,    0, 0, 0, 
            0,   0,    0, 0, 0]

formY: [ 0,  0,  3,  0,  0,
         0,  0,  3,  0,  0,
        -3, -3,  0,  0,  0,
         0,  0,  0,  0,  0,
         0,  0,  0,  0,  0]


